### ISSUE TITLE
จารวานรบกวนเพิ่ม Version EMA Backtest 2 เส้นให้ด้วยได้ไหมครับ

### ISSUE THREAD

**Issue by X48Github01** [vazw/VXMA-_BACKTEST#1]
จารย์ VAZ วานรบกวนเพิ่ม Version EMA Backtest 2 เส้นให้ด้วยได้ไหมครับ
ขอบพระคุณเป็นอย่างยิ่งสำหรับชาว MA Cross ^_^

**Comment by vazw** [comment]
[Backtesting 2EMA](https://github.com/vazw/VXMA-_BACKTEST/blob/main/backtest_2EMA.py) เรียบร้อยครับ ทดลองดูได้เลย
